name: Dotnet CI for Pull Request with SonarQube and Lint

on:
  pull_request:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-analyze:
    runs-on: windows-latest

    env:
      BUILD_CONFIGURATION: Release
      DOTNET_VERSION: '8.0.x'
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
      NUGET_FEED_URL: https://pkgs.dev.azure.com/amplify-artifact-org/ArtifactsProjectStore/_packaging/ArtifactsForGitHubWorkflows/nuget/v3/index.json
      NUGET_FEED_NAME: ArtifactsForGitHubWorkflows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Java for Sonar
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarQube Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Get Project Key from .csproj
        id: project_info
        shell: pwsh
        run: |
          [xml]$proj = Get-Content *.csproj
          $key = $proj.Project.PropertyGroup.AssemblyName
          if (-not $key) {
            $key = (Get-Item *.csproj).BaseName
          }
          echo "projectKey=$key" >> $env:GITHUB_OUTPUT

      - name: SonarQube PR Analysis Start
        run: |
          dotnet-sonarscanner begin `
            /k:"${{ steps.project_info.outputs.projectKey }}" `
            /d:sonar.token="${{ env.SONAR_TOKEN }}" `
            /d:sonar.host.url="http://amplify-platform-sonarqube.eastus.cloudapp.azure.com:9000" `
            /d:sonar.pullrequest.key=${{ github.event.pull_request.number }} `
            /d:sonar.pullrequest.branch=${{ github.head_ref }} `
            /d:sonar.pullrequest.base=${{ github.base_ref }} `
            /d:sonar.pullrequest.github.repository=${{ github.repository }}

      - name: Run Linting
        run: dotnet format --verify-no-changes --severity info

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: End SonarQube Analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

      - name: Pack NuGet Package
        run: |
          dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }} --output out

      - name: Push to Azure Artifacts
        run: |
          dotnet nuget push "out/*.nupkg" `
            --source "${{ env.NUGET_FEED_URL }}" `
            --api-key AzureArtifacts `
            --skip-duplicate
