name: Dotnet CI for Pull Request with SonarQube and Lint

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
      pullRequestNumber:
        required: false
        type: string
      pullRequestHead:
        required: false
        type: string
      pullRequestBase:
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      AZURE_ARTIFACTS_PAT:
        required: true
      GITHUB_REPO_PAT:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-analyze:
    runs-on: windows-latest

    env:
      BUILD_CONFIGURATION: Release
      DOTNET_VERSION: '8.0.x'
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
      GITHUB_REPO_PAT: ${{ secrets.GITHUB_REPO_PAT }}
      NUGET_FEED_URL: https://pkgs.dev.azure.com/amplify-artifact-org/ArtifactsProjectStore/_packaging/ArtifactsForGitHubWorkflows/nuget/v3/index.json
      NUGET_FEED_NAME: ArtifactsForGitHubWorkflows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_REPO_PAT }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Java for SonarQube
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarQube Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Configure NuGet Source with PAT
        run: |
          nuget sources remove -Name ${{ env.NUGET_FEED_NAME }} || true
          nuget sources add -Name ${{ env.NUGET_FEED_NAME }} `
            -Source "${{ env.NUGET_FEED_URL }}" `
            -Username "anyuser" `
            -Password "${{ env.AZURE_ARTIFACTS_PAT }}" `
            -StorePasswordInClearText

      - name: SonarQube PR Analysis Start
        run: |
          dotnet-sonarscanner begin `
            /k:"Amplify.WebApi.v1.Models" `
            /d:sonar.token="${{ env.SONAR_TOKEN }}" `
            /d:sonar.host.url="http://amplify-platform-sonarqube.eastus.cloudapp.azure.com:9000" `
            /d:sonar.pullrequest.key="${{ inputs.pullRequestNumber }}" `
            /d:sonar.pullrequest.branch="${{ inputs.pullRequestHead }}" `
            /d:sonar.pullrequest.base="${{ inputs.pullRequestBase }}" `
            /d:sonar.pullrequest.github.repository="${{ github.repository }}"

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.projectPath }} `
          --source "${{ env.NUGET_FEED_URL }}" `
          --source "https://api.nuget.org/v3/index.json"

      - name: Build Project
        run: dotnet build ${{ inputs.projectPath }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: End SonarQube Analysis
        run: dotnet-sonarscanner end /d:sonar.token="${{ env.SONAR_TOKEN }}"

      - name: Pack NuGet Package
        run: |
          dotnet pack ${{ inputs.projectPath }} --configuration ${{ env.BUILD_CONFIGURATION }} --output out

      - name: Push to Azure Artifacts
        run: |
          dotnet nuget push "out/*.nupkg" `
            --source "${{ env.NUGET_FEED_URL }}" `
            --api-key AzureArtifacts `
            --skip-duplicate
