name: Dotnet CI for Pull Request with Linting

on:
  workflow_call:
    inputs:
      projectPath:
        required: true
        type: string
    secrets:
      AZURE_ARTIFACTS_PAT:
        required: true
      GITHUB_REPO_PAT:
        required: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-analyze:
    runs-on: windows-latest

    env:
      BUILD_CONFIGURATION: Release
      DOTNET_VERSION: '8.0.x'
      AZURE_ARTIFACTS_PAT: ${{ secrets.AZURE_ARTIFACTS_PAT }}
      GITHUB_REPO_PAT: ${{ secrets.GITHUB_REPO_PAT }}
      NUGET_FEED_URL: https://pkgs.dev.azure.com/amplify-artifact-org/ArtifactsProjectStore/_packaging/ArtifactsForGitHubWorkflows/nuget/v3/index.json
      NUGET_FEED_NAME: ArtifactsForGitHubWorkflows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ env.GITHUB_REPO_PAT }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Configure NuGet Source with PAT
        run: |
          nuget sources remove -Name ${{ env.NUGET_FEED_NAME }} || true
          nuget sources add -Name ${{ env.NUGET_FEED_NAME }} `
            -Source "${{ env.NUGET_FEED_URL }}" `
            -Username "anyuser" `
            -Password "${{ env.AZURE_ARTIFACTS_PAT }}" `
            -StorePasswordInClearText

      - name: Run Linting (dotnet format)
        run: dotnet format ${{ inputs.projectPath }} --verify-no-changes --severity info

      - name: Restore Dependencies
        run: dotnet restore ${{ inputs.projectPath }} `
          --source "${{ env.NUGET_FEED_URL }}" `
          --source "https://api.nuget.org/v3/index.json"

      - name: Build Project
        run: dotnet build ${{ inputs.projectPath }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Pack NuGet Package
        run: |
          dotnet pack ${{ inputs.projectPath }} --configuration ${{ env.BUILD_CONFIGURATION }} --output out

      - name: Push to Azure Artifacts
        run: |
          dotnet nuget push "out/*.nupkg" `
            --source "${{ env.NUGET_FEED_URL }}" `
            --api-key AzureArtifacts `
            --skip-duplicate
